import { Poll, Opinion } from "@prisma/client";
import type { GetServerSideProps, NextPage } from "next";
import Image from "next/image";
import { useEffect, useState } from "react";
import { trpc } from "../../lib/trpc";
import puff from "../../public/puff.svg";
import { MdOutlineContentCopy } from "react-icons/md";
import { BsHeartFill } from "react-icons/bs";
import Head from "next/head";
import { tuple } from "zod";
//TODO handle votes

const Vote: NextPage = (props: any) => {
  const [voted, setVoted] = useState(false);
  const [calculating, setCalculating] = useState(false);
  const [pollData, setPollData] = useState<
    | (Poll & {
        opinions: Opinion[];
      })
    | null
  >();

  console.log(props.id);

  const getPoll = () => {};
  const { error, isLoading } = trpc.useQuery(
    ["get-poll", { id: props.id as string }],
    {
      onSuccess(data) {
        setPollData(data);
      },
    }
  );

  useEffect(() => {
    let isvoted = window.localStorage.getItem("voted");
    console.log(isvoted);
    if( isvoted == `true${props.id}`){
      setVoted(true);
    }else {
      setVoted(false);
    }
    console.log("voted", voted);
  }, []);
  const calculatePercentage = (count: number, total: number) => {
    if (count == 0 && total == 0) return 0;
    let percent = (count / total) * 100;

    return Math.round(percent);
  };

  const castvoteMutation = trpc.useMutation(["cast-vote"]);
  const castVote = (id: string, e: any) => {
    /* e.preventDefault(); */

    castvoteMutation
      .mutateAsync({ opinionId: id, pollId: props.id })
      .then((res) => {
        if (voted == false) {
          setVoted((voted) => !voted);
          localStorage.setItem("voted", `true${props.id}`);
        }
        setPollData(res);

        console.log({ "Updated Poll object": res });
      });
  };
  console.log("mutation is loading", castvoteMutation.isLoading);
  console.log(pollData);
  console.log("error", error);
  if (isLoading == true) {
    return (
      <div data-theme="synthwave" className="grid h-screen place-items-center">
        <Image
          src={puff}
          width={64}
          height={64}
          alt="loading..."
          className=""
        />
      </div>
    );
  }
  if (castvoteMutation.isLoading == true) {
    return (
      <div data-theme="synthwave" className="grid h-screen place-items-center">
        <p className="text-2xl font-nuto font-bold">Casting vote</p>
        <Image
          src={puff}
          width={64}
          height={64}
          alt="loading..."
          className=""
        />
      </div>
    );
  }
  return (
    <div data-theme="synthwave">
      <Head>
        <title>Pollage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid h-screen place-items-center">
        
        <button className="btn gap-2">
          Copy the link to this poll
          <MdOutlineContentCopy
            onClick={(e) => {
              navigator.clipboard.writeText(
                `https://pollage.vercel.app/vote/${props.id as string}`
              ); //TODO put correct url on production
            }}
          />
        </button>

        <p className="text-2xl font-titan">{pollData?.name}</p>
        <div className="flex m-5 ">
          <div className="flex flex-col  ">
            <button
              disabled={voted}
              className="bg-[#F5F5F5] justify-center flex rounded-xl border-2 border-[#808080] h-28 max-w-xs btn btn-outline btn-primary"
              onClick={(e) => {
                castVote(pollData!.opinions[0]!.id, e);
              }}
            >
              {`Vote ${pollData?.opinions[0].description}`}
            </button>
            <div className="flex justify-center">
              <p className="mt-6">
                {calculatePercentage(
                  pollData?.opinions[0].count!,
                  pollData?.opinions[0].count! + pollData?.opinions[1].count!
                )}
                %
              </p>
            </div>
          </div>
          <p className="m-10 font-bold">vs</p>
          <div className="flex flex-col">
            <button
              disabled={voted}
              className="bg-[#F5F5F5] justify-center flex border-2 rounded-xl border-[#808080] h-28 max-w-xs btn btn-outline btn-primary"
              onClick={(e) => {
                castVote(pollData!.opinions[1]!.id, e);
              }}
            >
              {`Vote ${pollData?.opinions[1].description}`}
            </button>
            <div className="flex justify-center">
              <p className="mt-6">
                {calculatePercentage(
                  pollData?.opinions[1].count!,
                  pollData?.opinions[0].count! + pollData?.opinions[1].count!
                )}{" "}
                %
              </p>
            </div>
          </div>
        </div>
      </div>
      <footer className="footer footer-center p-4 bg-base-300 text-base-content">
        <div className="flex flex-row">
          <h3>From Github with</h3> <BsHeartFill className="bg-red m-1" />
        </div>
      </footer>
    </div>
  );
};
export default Vote;
export const getServerSideProps: GetServerSideProps = async ({ params }) => {
  let id = params?.id as string;
  console.log(id);
  return { props: { id } };
};
